// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api-proto/onboarding/login/login.proto

package loginpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	UsernameEmail        string   `protobuf:"bytes,1,opt,name=username_email,json=usernameEmail,proto3" json:"username_email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9c7fb44ee5d7ba, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsernameEmail() string {
	if m != nil {
		return m.UsernameEmail
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9c7fb44ee5d7ba, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "loginpb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "loginpb.LoginResponse")
}

func init() {
	proto.RegisterFile("api-proto/onboarding/login/login.proto", fileDescriptor_2c9c7fb44ee5d7ba)
}

var fileDescriptor_2c9c7fb44ee5d7ba = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0xe9, 0xfa, 0x67, 0x35, 0xee, 0x2e, 0x12, 0x51, 0x6a, 0xf1, 0xa0, 0x05, 0x45, 0x04,
	0x1b, 0xd4, 0x9b, 0x77, 0x6f, 0x5e, 0xac, 0x7a, 0x13, 0xd6, 0x69, 0x3b, 0x94, 0x60, 0x9b, 0x89,
	0x99, 0xee, 0x7a, 0xf7, 0x15, 0x7c, 0x34, 0x5f, 0xc1, 0x07, 0x91, 0xa6, 0xad, 0xc8, 0x5e, 0x42,
	0xbe, 0x5f, 0xbe, 0x7c, 0xcc, 0x7c, 0xe2, 0x0c, 0xac, 0xbe, 0xb4, 0x8e, 0x1a, 0x52, 0x64, 0x32,
	0x02, 0x57, 0x68, 0x53, 0xaa, 0x8a, 0x4a, 0x6d, 0xba, 0x33, 0xf1, 0x8f, 0x72, 0xec, 0x85, 0xcd,
	0xa2, 0xa3, 0x92, 0xa8, 0xac, 0x50, 0x81, 0xd5, 0x0a, 0x8c, 0xa1, 0x06, 0x1a, 0x4d, 0x86, 0x3b,
	0x5b, 0xfc, 0x20, 0x26, 0xf7, 0xad, 0x31, 0xc5, 0xf7, 0x05, 0x72, 0x23, 0x4f, 0xc5, 0x6c, 0xc1,
	0xe8, 0x0c, 0xd4, 0x38, 0xc7, 0x1a, 0x74, 0x15, 0x06, 0xc7, 0xc1, 0xf9, 0x76, 0x3a, 0x1d, 0xe8,
	0x5d, 0x0b, 0x65, 0x24, 0xb6, 0x2c, 0x30, 0x7f, 0x90, 0x2b, 0xc2, 0x91, 0x37, 0xfc, 0xe9, 0xf8,
	0x55, 0x4c, 0xfb, 0x48, 0xb6, 0x64, 0x18, 0x65, 0x28, 0xc6, 0x35, 0x32, 0x43, 0x89, 0x7d, 0xd8,
	0x20, 0xa5, 0x14, 0xeb, 0x39, 0x15, 0xe8, 0x23, 0x36, 0x52, 0x7f, 0x97, 0x27, 0x62, 0x02, 0x79,
	0x8e, 0xcc, 0xf3, 0x86, 0xde, 0xd0, 0x84, 0x6b, 0xfe, 0xcb, 0x4e, 0xc7, 0x9e, 0x5a, 0x74, 0x5d,
	0xf5, 0x43, 0x3f, 0xa2, 0x5b, 0xea, 0x1c, 0xe5, 0x8b, 0xd8, 0xf5, 0xfa, 0x99, 0xd1, 0x0d, 0x6c,
	0x3f, 0xe9, 0x0b, 0x48, 0xfe, 0xef, 0x17, 0x1d, 0xac, 0xe2, 0x6e, 0xc6, 0xf8, 0xf0, 0xf3, 0xfb,
	0xe7, 0x6b, 0xb4, 0x17, 0xcf, 0xd4, 0xf2, 0x4a, 0xb5, 0xbb, 0x76, 0x65, 0xde, 0x06, 0x17, 0xd9,
	0xa6, 0x6f, 0xea, 0xe6, 0x37, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x10, 0x7b, 0x43, 0x7a, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginServiceClient interface {
	LoginUserService(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type loginServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoginServiceClient(cc *grpc.ClientConn) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) LoginUserService(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/loginpb.LoginService/LoginUserService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
type LoginServiceServer interface {
	LoginUserService(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterLoginServiceServer(s *grpc.Server, srv LoginServiceServer) {
	s.RegisterService(&_LoginService_serviceDesc, srv)
}

func _LoginService_LoginUserService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).LoginUserService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loginpb.LoginService/LoginUserService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).LoginUserService(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "loginpb.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginUserService",
			Handler:    _LoginService_LoginUserService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api-proto/onboarding/login/login.proto",
}
