// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api-proto/webhooks/git/github.proto

package githubpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GithubPushWebhookRequest struct {
	Ref                  string           `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Head                 string           `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Before               string           `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	Size                 int32            `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	DistinctSize         int32            `protobuf:"varint,5,opt,name=distinct_size,json=distinctSize,proto3" json:"distinct_size,omitempty"`
	Commits              []*GithubCommits `protobuf:"bytes,6,rep,name=commits,proto3" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GithubPushWebhookRequest) Reset()         { *m = GithubPushWebhookRequest{} }
func (m *GithubPushWebhookRequest) String() string { return proto.CompactTextString(m) }
func (*GithubPushWebhookRequest) ProtoMessage()    {}
func (*GithubPushWebhookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_925fa4d49b90e0de, []int{0}
}

func (m *GithubPushWebhookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GithubPushWebhookRequest.Unmarshal(m, b)
}
func (m *GithubPushWebhookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GithubPushWebhookRequest.Marshal(b, m, deterministic)
}
func (m *GithubPushWebhookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GithubPushWebhookRequest.Merge(m, src)
}
func (m *GithubPushWebhookRequest) XXX_Size() int {
	return xxx_messageInfo_GithubPushWebhookRequest.Size(m)
}
func (m *GithubPushWebhookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GithubPushWebhookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GithubPushWebhookRequest proto.InternalMessageInfo

func (m *GithubPushWebhookRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *GithubPushWebhookRequest) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *GithubPushWebhookRequest) GetBefore() string {
	if m != nil {
		return m.Before
	}
	return ""
}

func (m *GithubPushWebhookRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GithubPushWebhookRequest) GetDistinctSize() int32 {
	if m != nil {
		return m.DistinctSize
	}
	return 0
}

func (m *GithubPushWebhookRequest) GetCommits() []*GithubCommits {
	if m != nil {
		return m.Commits
	}
	return nil
}

type GithubCommits struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TreeId               string   `protobuf:"bytes,2,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Distinct             bool     `protobuf:"varint,3,opt,name=distinct,proto3" json:"distinct,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            string   `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Url                  string   `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GithubCommits) Reset()         { *m = GithubCommits{} }
func (m *GithubCommits) String() string { return proto.CompactTextString(m) }
func (*GithubCommits) ProtoMessage()    {}
func (*GithubCommits) Descriptor() ([]byte, []int) {
	return fileDescriptor_925fa4d49b90e0de, []int{1}
}

func (m *GithubCommits) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GithubCommits.Unmarshal(m, b)
}
func (m *GithubCommits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GithubCommits.Marshal(b, m, deterministic)
}
func (m *GithubCommits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GithubCommits.Merge(m, src)
}
func (m *GithubCommits) XXX_Size() int {
	return xxx_messageInfo_GithubCommits.Size(m)
}
func (m *GithubCommits) XXX_DiscardUnknown() {
	xxx_messageInfo_GithubCommits.DiscardUnknown(m)
}

var xxx_messageInfo_GithubCommits proto.InternalMessageInfo

func (m *GithubCommits) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GithubCommits) GetTreeId() string {
	if m != nil {
		return m.TreeId
	}
	return ""
}

func (m *GithubCommits) GetDistinct() bool {
	if m != nil {
		return m.Distinct
	}
	return false
}

func (m *GithubCommits) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GithubCommits) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *GithubCommits) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CommonResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_925fa4d49b90e0de, []int{2}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CommonResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*GithubPushWebhookRequest)(nil), "githubpb.GithubPushWebhookRequest")
	proto.RegisterType((*GithubCommits)(nil), "githubpb.GithubCommits")
	proto.RegisterType((*CommonResponse)(nil), "githubpb.CommonResponse")
}

func init() {
	proto.RegisterFile("api-proto/webhooks/git/github.proto", fileDescriptor_925fa4d49b90e0de)
}

var fileDescriptor_925fa4d49b90e0de = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x3d, 0xce, 0xd3, 0x40,
	0x10, 0xd5, 0x3a, 0x89, 0x13, 0x0f, 0x24, 0xa0, 0x15, 0x90, 0xc5, 0x4a, 0x11, 0x39, 0x4d, 0x84,
	0x44, 0xac, 0x84, 0x8e, 0x82, 0x06, 0x09, 0x94, 0x0e, 0x6d, 0x0a, 0xca, 0xc8, 0x3f, 0x13, 0x7b,
	0x45, 0xec, 0x35, 0xde, 0x75, 0x90, 0x28, 0x39, 0x00, 0x0d, 0x3d, 0xa7, 0xe1, 0x06, 0x5c, 0x81,
	0x83, 0x20, 0xef, 0xda, 0x84, 0x7c, 0x5f, 0x61, 0x69, 0xde, 0xbc, 0xa7, 0xf1, 0x7b, 0x33, 0x0b,
	0xab, 0xa8, 0x12, 0x2f, 0xab, 0x5a, 0x6a, 0x19, 0x7e, 0xc1, 0x38, 0x97, 0xf2, 0x93, 0x0a, 0x33,
	0xa1, 0xdb, 0x2f, 0x6f, 0xe2, 0x8d, 0x61, 0xe8, 0xc4, 0xa2, 0x2a, 0xf6, 0x17, 0x99, 0x94, 0xd9,
	0x19, 0xc3, 0xa8, 0x12, 0x61, 0x54, 0x96, 0x52, 0x47, 0x5a, 0xc8, 0x52, 0x59, 0x5d, 0xf0, 0x8b,
	0x00, 0x7b, 0x6f, 0xa4, 0x1f, 0x1a, 0x95, 0x7f, 0xb4, 0xf3, 0x38, 0x7e, 0x6e, 0x50, 0x69, 0xfa,
	0x18, 0x06, 0x35, 0x9e, 0x18, 0x59, 0x92, 0xb5, 0xc7, 0xdb, 0x92, 0x52, 0x18, 0xe6, 0x18, 0xa5,
	0xcc, 0x31, 0x2d, 0x53, 0xd3, 0x67, 0xe0, 0xc6, 0x78, 0x92, 0x35, 0xb2, 0x81, 0xe9, 0x76, 0xa8,
	0xd5, 0x2a, 0xf1, 0x15, 0xd9, 0x70, 0x49, 0xd6, 0x23, 0x6e, 0x6a, 0xba, 0x82, 0x69, 0x2a, 0x94,
	0x16, 0x65, 0xa2, 0x8f, 0x86, 0x1c, 0x19, 0xf2, 0x61, 0xdf, 0x3c, 0xb4, 0xa2, 0x2d, 0x8c, 0x13,
	0x59, 0x14, 0x42, 0x2b, 0xe6, 0x2e, 0x07, 0xeb, 0x07, 0xbb, 0xf9, 0xa6, 0x4f, 0xb3, 0xb1, 0x5e,
	0xdf, 0x5a, 0x9a, 0xf7, 0xba, 0xe0, 0x27, 0x81, 0xe9, 0x0d, 0x45, 0x67, 0xe0, 0x88, 0xb4, 0xb3,
	0xee, 0x88, 0x94, 0xce, 0x61, 0xac, 0x6b, 0xc4, 0xa3, 0xe8, 0xcd, 0xbb, 0x2d, 0xdc, 0xa7, 0xd4,
	0x87, 0x49, 0xff, 0x77, 0x13, 0x60, 0xc2, 0xff, 0x61, 0xca, 0x60, 0x5c, 0xa0, 0x52, 0x51, 0x66,
	0x53, 0x78, 0xbc, 0x87, 0x74, 0x01, 0x9e, 0x16, 0x05, 0x2a, 0x1d, 0x15, 0x95, 0x09, 0xe1, 0xf1,
	0x6b, 0xa3, 0x5d, 0x5c, 0x53, 0x9f, 0x99, 0x6b, 0x17, 0xd7, 0xd4, 0xe7, 0xe0, 0x0d, 0xcc, 0x5a,
	0x67, 0xb2, 0xe4, 0xa8, 0x2a, 0x59, 0x2a, 0xfc, 0x7f, 0x36, 0xb9, 0x9d, 0x4d, 0x61, 0x98, 0xc8,
	0x14, 0x8d, 0xcf, 0x11, 0x37, 0xf5, 0xee, 0x3b, 0x81, 0xa7, 0x36, 0x60, 0x77, 0xa3, 0x03, 0xd6,
	0x17, 0x91, 0xa0, 0xa2, 0x0d, 0x3c, 0x7f, 0x87, 0x3a, 0xc9, 0xaf, 0x57, 0xb4, 0x2b, 0xd8, 0x97,
	0x27, 0x49, 0x83, 0xbb, 0x9b, 0xbb, 0x7f, 0x65, 0x9f, 0x5d, 0x35, 0xb7, 0x16, 0x03, 0xff, 0xdb,
	0xef, 0x3f, 0x3f, 0x9c, 0x27, 0xc1, 0xa3, 0xf0, 0xb2, 0xed, 0x9e, 0x57, 0x58, 0x35, 0x2a, 0x7f,
	0x4d, 0x5e, 0xc4, 0xae, 0x79, 0x3f, 0xaf, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x7a, 0xad,
	0xa6, 0x8e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GithubWebhookServicesClient is the client API for GithubWebhookServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GithubWebhookServicesClient interface {
	FetchGithubPushCommitInfo(ctx context.Context, in *GithubPushWebhookRequest, opts ...grpc.CallOption) (*CommonResponse, error)
}

type githubWebhookServicesClient struct {
	cc *grpc.ClientConn
}

func NewGithubWebhookServicesClient(cc *grpc.ClientConn) GithubWebhookServicesClient {
	return &githubWebhookServicesClient{cc}
}

func (c *githubWebhookServicesClient) FetchGithubPushCommitInfo(ctx context.Context, in *GithubPushWebhookRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/githubpb.GithubWebhookServices/FetchGithubPushCommitInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GithubWebhookServicesServer is the server API for GithubWebhookServices service.
type GithubWebhookServicesServer interface {
	FetchGithubPushCommitInfo(context.Context, *GithubPushWebhookRequest) (*CommonResponse, error)
}

func RegisterGithubWebhookServicesServer(s *grpc.Server, srv GithubWebhookServicesServer) {
	s.RegisterService(&_GithubWebhookServices_serviceDesc, srv)
}

func _GithubWebhookServices_FetchGithubPushCommitInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GithubPushWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubWebhookServicesServer).FetchGithubPushCommitInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/githubpb.GithubWebhookServices/FetchGithubPushCommitInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubWebhookServicesServer).FetchGithubPushCommitInfo(ctx, req.(*GithubPushWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GithubWebhookServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "githubpb.GithubWebhookServices",
	HandlerType: (*GithubWebhookServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchGithubPushCommitInfo",
			Handler:    _GithubWebhookServices_FetchGithubPushCommitInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api-proto/webhooks/git/github.proto",
}
