// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api-proto/home/home.proto

package homepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VerifyUserRequest struct {
	// Types that are valid to be assigned to VerifyUser:
	//	*VerifyUserRequest_Info
	//	*VerifyUserRequest_FileChunk
	VerifyUser           isVerifyUserRequest_VerifyUser `protobuf_oneof:"verify_user"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *VerifyUserRequest) Reset()         { *m = VerifyUserRequest{} }
func (m *VerifyUserRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyUserRequest) ProtoMessage()    {}
func (*VerifyUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43564b565565fc99, []int{0}
}

func (m *VerifyUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserRequest.Unmarshal(m, b)
}
func (m *VerifyUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserRequest.Marshal(b, m, deterministic)
}
func (m *VerifyUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserRequest.Merge(m, src)
}
func (m *VerifyUserRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyUserRequest.Size(m)
}
func (m *VerifyUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserRequest proto.InternalMessageInfo

type isVerifyUserRequest_VerifyUser interface {
	isVerifyUserRequest_VerifyUser()
}

type VerifyUserRequest_Info struct {
	Info *UserInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type VerifyUserRequest_FileChunk struct {
	FileChunk []byte `protobuf:"bytes,2,opt,name=file_chunk,json=fileChunk,proto3,oneof"`
}

func (*VerifyUserRequest_Info) isVerifyUserRequest_VerifyUser() {}

func (*VerifyUserRequest_FileChunk) isVerifyUserRequest_VerifyUser() {}

func (m *VerifyUserRequest) GetVerifyUser() isVerifyUserRequest_VerifyUser {
	if m != nil {
		return m.VerifyUser
	}
	return nil
}

func (m *VerifyUserRequest) GetInfo() *UserInfo {
	if x, ok := m.GetVerifyUser().(*VerifyUserRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (m *VerifyUserRequest) GetFileChunk() []byte {
	if x, ok := m.GetVerifyUser().(*VerifyUserRequest_FileChunk); ok {
		return x.FileChunk
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*VerifyUserRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _VerifyUserRequest_OneofMarshaler, _VerifyUserRequest_OneofUnmarshaler, _VerifyUserRequest_OneofSizer, []interface{}{
		(*VerifyUserRequest_Info)(nil),
		(*VerifyUserRequest_FileChunk)(nil),
	}
}

func _VerifyUserRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*VerifyUserRequest)
	// verify_user
	switch x := m.VerifyUser.(type) {
	case *VerifyUserRequest_Info:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Info); err != nil {
			return err
		}
	case *VerifyUserRequest_FileChunk:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.FileChunk)
	case nil:
	default:
		return fmt.Errorf("VerifyUserRequest.VerifyUser has unexpected type %T", x)
	}
	return nil
}

func _VerifyUserRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*VerifyUserRequest)
	switch tag {
	case 1: // verify_user.info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserInfo)
		err := b.DecodeMessage(msg)
		m.VerifyUser = &VerifyUserRequest_Info{msg}
		return true, err
	case 2: // verify_user.file_chunk
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.VerifyUser = &VerifyUserRequest_FileChunk{x}
		return true, err
	default:
		return false, nil
	}
}

func _VerifyUserRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*VerifyUserRequest)
	// verify_user
	switch x := m.VerifyUser.(type) {
	case *VerifyUserRequest_Info:
		s := proto.Size(x.Info)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *VerifyUserRequest_FileChunk:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.FileChunk)))
		n += len(x.FileChunk)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type UserInfo struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lan                  float64  `protobuf:"fixed64,3,opt,name=lan,proto3" json:"lan,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_43564b565565fc99, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *UserInfo) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *UserInfo) GetLan() float64 {
	if m != nil {
		return m.Lan
	}
	return 0
}

func (m *UserInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type VerifyUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserResponse) Reset()         { *m = VerifyUserResponse{} }
func (m *VerifyUserResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyUserResponse) ProtoMessage()    {}
func (*VerifyUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_43564b565565fc99, []int{2}
}

func (m *VerifyUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserResponse.Unmarshal(m, b)
}
func (m *VerifyUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserResponse.Marshal(b, m, deterministic)
}
func (m *VerifyUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserResponse.Merge(m, src)
}
func (m *VerifyUserResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyUserResponse.Size(m)
}
func (m *VerifyUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserResponse proto.InternalMessageInfo

func (m *VerifyUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VerifyUserResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*VerifyUserRequest)(nil), "homepb.VerifyUserRequest")
	proto.RegisterType((*UserInfo)(nil), "homepb.UserInfo")
	proto.RegisterType((*VerifyUserResponse)(nil), "homepb.VerifyUserResponse")
}

func init() { proto.RegisterFile("api-proto/home/home.proto", fileDescriptor_43564b565565fc99) }

var fileDescriptor_43564b565565fc99 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4e, 0xfa, 0x40,
	0x10, 0xc7, 0x29, 0xf0, 0xe3, 0x27, 0x03, 0x44, 0xd8, 0x78, 0x28, 0x8d, 0x89, 0xd8, 0x83, 0x21,
	0x26, 0xd2, 0x88, 0x37, 0x8f, 0x78, 0xc1, 0x6b, 0xfd, 0x73, 0x25, 0x4b, 0x99, 0xc2, 0xa6, 0xb0,
	0x5b, 0x3b, 0x4b, 0x13, 0xae, 0xbe, 0x82, 0x8f, 0xe6, 0x2b, 0xf8, 0x20, 0x66, 0x77, 0x6d, 0xa2,
	0xd1, 0x4b, 0x33, 0xf3, 0x99, 0xc9, 0x67, 0xda, 0x6f, 0x61, 0xc8, 0x73, 0x71, 0x95, 0x17, 0x4a,
	0xab, 0x68, 0xa3, 0x76, 0x68, 0x1f, 0x13, 0xdb, 0xb3, 0x96, 0xa9, 0xf3, 0x65, 0x70, 0xba, 0x56,
	0x6a, 0xbd, 0xc5, 0x88, 0xe7, 0x22, 0xe2, 0x52, 0x2a, 0xcd, 0xb5, 0x50, 0x92, 0xdc, 0x56, 0x98,
	0xc1, 0xe0, 0x19, 0x0b, 0x91, 0x1e, 0x9e, 0x08, 0x8b, 0x18, 0x5f, 0xf6, 0x48, 0x9a, 0x5d, 0x40,
	0x53, 0xc8, 0x54, 0xf9, 0xde, 0xc8, 0x1b, 0x77, 0xa6, 0xfd, 0x89, 0x33, 0x4d, 0xcc, 0xca, 0xbd,
	0x4c, 0xd5, 0xbc, 0x16, 0xdb, 0x39, 0x3b, 0x03, 0x48, 0xc5, 0x16, 0x17, 0xc9, 0x66, 0x2f, 0x33,
	0xbf, 0x3e, 0xf2, 0xc6, 0xdd, 0x79, 0x2d, 0x6e, 0x1b, 0x76, 0x67, 0xd0, 0xac, 0x07, 0x9d, 0xd2,
	0xda, 0x17, 0x7b, 0xc2, 0x22, 0xcc, 0xe0, 0xa8, 0x72, 0xb0, 0x73, 0xe8, 0xf2, 0x24, 0x41, 0xa2,
	0x85, 0x56, 0x19, 0x4a, 0x7b, 0xab, 0x1d, 0x77, 0x1c, 0x7b, 0x34, 0x88, 0xf5, 0xa1, 0xb1, 0xe5,
	0xda, 0x7a, 0xbd, 0xd8, 0x94, 0x8e, 0x48, 0xbf, 0x51, 0x11, 0xc9, 0x7c, 0xf8, 0xcf, 0x57, 0xab,
	0x02, 0x89, 0xfc, 0xa6, 0x35, 0x54, 0x6d, 0x38, 0x03, 0xf6, 0xfd, 0xcb, 0x28, 0x57, 0x92, 0xd0,
	0xec, 0xef, 0x90, 0x88, 0xaf, 0xf1, 0xeb, 0x62, 0xd5, 0x32, 0x06, 0xcd, 0x44, 0xad, 0xd0, 0x9e,
	0xfb, 0x17, 0xdb, 0x7a, 0x7a, 0x80, 0x9e, 0x73, 0x3c, 0x60, 0x51, 0x8a, 0x04, 0xd9, 0x06, 0x06,
	0x46, 0xf7, 0x13, 0x0e, 0xab, 0x80, 0x7e, 0x25, 0x19, 0x04, 0x7f, 0x8d, 0xdc, 0xab, 0x84, 0xc1,
	0xeb, 0xfb, 0xc7, 0x5b, 0xfd, 0x24, 0x3c, 0x8e, 0xca, 0xeb, 0xc8, 0xe4, 0x13, 0xb9, 0xac, 0x6e,
	0xbd, 0xcb, 0xb1, 0xb7, 0x6c, 0xd9, 0xff, 0x73, 0xf3, 0x19, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xb4,
	0x67, 0x5b, 0xe2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VerifyServiceClient is the client API for VerifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerifyServiceClient interface {
	UserVerifyService(ctx context.Context, opts ...grpc.CallOption) (VerifyService_UserVerifyServiceClient, error)
}

type verifyServiceClient struct {
	cc *grpc.ClientConn
}

func NewVerifyServiceClient(cc *grpc.ClientConn) VerifyServiceClient {
	return &verifyServiceClient{cc}
}

func (c *verifyServiceClient) UserVerifyService(ctx context.Context, opts ...grpc.CallOption) (VerifyService_UserVerifyServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VerifyService_serviceDesc.Streams[0], "/homepb.VerifyService/UserVerifyService", opts...)
	if err != nil {
		return nil, err
	}
	x := &verifyServiceUserVerifyServiceClient{stream}
	return x, nil
}

type VerifyService_UserVerifyServiceClient interface {
	Send(*VerifyUserRequest) error
	CloseAndRecv() (*VerifyUserResponse, error)
	grpc.ClientStream
}

type verifyServiceUserVerifyServiceClient struct {
	grpc.ClientStream
}

func (x *verifyServiceUserVerifyServiceClient) Send(m *VerifyUserRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *verifyServiceUserVerifyServiceClient) CloseAndRecv() (*VerifyUserResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(VerifyUserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VerifyServiceServer is the server API for VerifyService service.
type VerifyServiceServer interface {
	UserVerifyService(VerifyService_UserVerifyServiceServer) error
}

func RegisterVerifyServiceServer(s *grpc.Server, srv VerifyServiceServer) {
	s.RegisterService(&_VerifyService_serviceDesc, srv)
}

func _VerifyService_UserVerifyService_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VerifyServiceServer).UserVerifyService(&verifyServiceUserVerifyServiceServer{stream})
}

type VerifyService_UserVerifyServiceServer interface {
	SendAndClose(*VerifyUserResponse) error
	Recv() (*VerifyUserRequest, error)
	grpc.ServerStream
}

type verifyServiceUserVerifyServiceServer struct {
	grpc.ServerStream
}

func (x *verifyServiceUserVerifyServiceServer) SendAndClose(m *VerifyUserResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *verifyServiceUserVerifyServiceServer) Recv() (*VerifyUserRequest, error) {
	m := new(VerifyUserRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _VerifyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "homepb.VerifyService",
	HandlerType: (*VerifyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UserVerifyService",
			Handler:       _VerifyService_UserVerifyService_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api-proto/home/home.proto",
}
